architecture-beta
    group external(cloud)[External]
    group internal(server)[aspire network]

    service internet(cloud)[Internet] in external
    service nocturne_postgres_server(database)[nocturne postgres server] in internal
    service nocturne_api(server)[nocturne api] in internal
    group nocturne_web_group(server)[nocturne web] in internal
    service nocturne_web_bff(server)[BFF] in nocturne_web_group
    service nocturne_web_frontend(disk)[Frontend] in nocturne_web_group
    service scalar(disk)[scalar] in internal
    service scalar_bootstrap(server)[scalar bootstrap] in internal
    service gateway(server)[gateway 8080] in external

    internet:R --> L:gateway
    nocturne_api:R --> L:nocturne_postgres_server
    nocturne_api:R --> L:nocturne_web_bff
    nocturne_web_bff:R --> L:nocturne_api
    nocturne_web_bff:R --> L:nocturne_postgres_server
    gateway:R --> L:nocturne_api
    gateway:R --> L:nocturne_web_frontend
    nocturne_web_frontend:R --> L:nocturne_web_bff